name: myhighst_map_app_v2
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  turf: ^0.0.8
  google_navigation_flutter: ^0.6.2
#  google_maps_flutter: ^2.5.0
  google_place: ^0.4.7
  flutter_riverpod: ^3.0.0-dev.16
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  http: ^0.13.3
  dio: ^5.3.2
  flutter_polyline_points: ^1.0.0
  uuid: ^4.2.1

  #Icons
  iconsax_flutter: ^1.0.1
  cupertino_icons: ^1.0.8
  flutter_sliding_box: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0

flutter:  
  uses-material-design: true

#dependency_overrides:
#  http:
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
